# By Meer Sawood <msawood@redhat.com> 
# uses ubi minimal image to build and httpd as the server

# Use an official Red Hat UBI minimal runtime as a parent image
FROM nginx:alpine

# Set the working directory to /app
#WORKDIR /app
#USER root
# Install dependencies
#RUN microdnf install nginx 

# Copy the default Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the server on port 80
EXPOSE 80

# Start Server
CMD [ "nginx", "-g", "daemon off;"]


