version: "3.9"
services:
  mamun-site:
    build: .
    ports:
      - "3000:3000"
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    depends_on:
     - mamun-site
    ports:
      -  "80:80"

