import Head from 'next/head'
import Header from '@/components/header'
import { Inter } from 'next/font/google'
import Hero from '@/components/hero'
import Layout from '@/components/layout'
import About from '@/components/about'
import Services from '@/components/services'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ma&rsquo;mun!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div id='home'>
        <Hero />
        </div>
        <div id='services'>
        <Services />
        </div>
        <div id='about'>
        <About />
        </div>
      </Layout>
    </>
  )
}
